# Generated by Django 4.1.6 on 2024-09-20 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='usuario',
            field=models.CharField(default='default_user', max_length=20),
        ),
    ]
