# Generated by Django 5.1.1 on 2024-09-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluno', models.CharField(max_length=200)),
                ('item', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Nota',
        ),
    ]
