# Generated by Django 4.1.6 on 2024-09-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_item_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='usuario',
            field=models.CharField(max_length=200),
        ),
    ]
